### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by tugsem** [bizip/ruby-capstone-catalog#15]
The link to the project : https://github.com/bizip/ruby-capstone-catalog/projects/1#card-84831376
- Team Member 1: @tugsem 
- Team Member 2: @bizip 
- Team Member 3: @Ghilain

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [x] Please make sure that all tasks are assigned to a team member. Currently, #9 task doesn't have anyone assigned to it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghilain** [comment]
Thank you @ShadyShawkat we have done it

**Comment by KDlamini** [comment]
### Hi team @Ghilain, @tugsem, @bizip 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your Kanban Board is complete!
Congratulations!!!

## HIGHLIGHTS 🌟 

# Status: Approved ✔️ 

![simon](https://user-images.githubusercontent.com/38088818/183476995-78aefbfd-d521-4c5b-90ac-4370a5bcbd1a.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghilain** [comment]
thank you @KDlamini
